In [58]:
import os
import numpy as np


1. Create a 5 × 5 NumPy matrix containing numbers from 1 to 25 and
print:
○ The first row
○ The last column
○ The diagonal elements

In [64]:
df = np.arange(25)
df = np.reshape(df,(5, 5))

df



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
df[0:1]

array([[0, 1, 2, 3, 4]])

In [61]:
df[0:,4:5]


array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

In [67]:
diagonal = np.diag(df)
diagonal

array([ 0,  6, 12, 18, 24])

2. Create two 3 × 3 matrices and perform matrix addition, subtraction,
and matrix multiplication.


In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[11,12,13],
              [14,15,16],
              [17,18,19]])
print(c)
print("Addition")
print(a+b)

print("Subtraction")
print(a-b)

print("Multiplication")
print(a*b)
print("Matrix multiplication")
print(np.matmul(a,b))

[1 2 2 3]
Addition
[[12 14 16]
 [18 20 22]
 [24 26 28]]
Subtraction
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
Multiplication
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
Matrix multiplication
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


3. Create a NumPy array of numbers from 1 to 100 and print all numbers
divisible by 3 using Boolean indexing.


In [99]:
arr = np.arange(1,101)
arr 
divisible_by_3 = arr[arr%3==0] 
print("numbers")
print(divisible_by_3)


numbers
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


4. Create a 4 × 4 matrix and replace all even numbers with 0

In [112]:
arr =np.arange(16)
arr =np.reshape(arr,(4,4))
arr
arr[arr%2==0] =0

print(arr)




[[ 0  1  0  3]
 [ 0  5  0  7]
 [ 0  9  0 11]
 [ 0 13  0 15]]


5. Create a 5 × 5 matrix of random integers and find:
○ Maximum value
○ Minimum value
○ Mean
○ Median

In [137]:
arr =np.random.rand(25)
arr=np.reshape(arr,(5,5))
arr



array([[0.20628629, 0.73960602, 0.61681502, 0.99865822, 0.78353931],
       [0.11645807, 0.28968694, 0.05650771, 0.18845307, 0.38350196],
       [0.93975915, 0.7452175 , 0.779871  , 0.86582249, 0.26431253],
       [0.8978292 , 0.85334901, 0.96587291, 0.00491296, 0.09842877],
       [0.66895481, 0.43839776, 0.00105736, 0.68127789, 0.64856604]])

In [138]:
np.max(arr)


np.float64(0.9986582207545945)

In [139]:
np.min(arr)

np.float64(0.0010573607362353021)

In [140]:
np.mean(arr)

np.float64(0.5293256791313622)

In [141]:
np.median(arr)

np.float64(0.6485660384867119)

6. Create a NumPy array containing 20 random numbers and sort it in
ascending and descending order

In [149]:
arr = np.random.rand(20)
arr

array([0.18840247, 0.76936479, 0.63556802, 0.83599007, 0.67428349,
       0.67069103, 0.17794627, 0.70399018, 0.10020726, 0.88944648,
       0.28424093, 0.52700653, 0.27050248, 0.07079896, 0.82945151,
       0.71960937, 0.25829869, 0.71754605, 0.2699155 , 0.3344034 ])

In [150]:
np.sort(arr)


array([0.07079896, 0.10020726, 0.17794627, 0.18840247, 0.25829869,
       0.2699155 , 0.27050248, 0.28424093, 0.3344034 , 0.52700653,
       0.63556802, 0.67069103, 0.67428349, 0.70399018, 0.71754605,
       0.71960937, 0.76936479, 0.82945151, 0.83599007, 0.88944648])

In [159]:
np.sort(arr)[::-1]


array([0.88944648, 0.83599007, 0.82945151, 0.76936479, 0.71960937,
       0.71754605, 0.70399018, 0.67428349, 0.67069103, 0.63556802,
       0.52700653, 0.3344034 , 0.28424093, 0.27050248, 0.2699155 ,
       0.25829869, 0.18840247, 0.17794627, 0.10020726, 0.07079896])

7. Create a 6 × 6 matrix and print:
○ Main diagonal
○ Upper triangular part
○ Lower triangular part

In [163]:
arr =np.random.rand(36).reshape(6,6)
arr


array([[0.53481906, 0.18128046, 0.52370394, 0.20741472, 0.96021535,
        0.17722208],
       [0.76153439, 0.71901005, 0.79180779, 0.95237685, 0.52255864,
        0.03486268],
       [0.18043538, 0.44763899, 0.90377474, 0.86442553, 0.28793317,
        0.80192044],
       [0.46966386, 0.43416453, 0.32167581, 0.16058274, 0.67493355,
        0.18469104],
       [0.18593542, 0.65227212, 0.87730055, 0.78394231, 0.45512626,
        0.33510941],
       [0.10686434, 0.33274041, 0.42080667, 0.74802713, 0.41163675,
        0.02514422]])

In [167]:
np.diag(arr)

array([0.53481906, 0.71901005, 0.90377474, 0.16058274, 0.45512626,
       0.02514422])

In [165]:
np.triu(arr)

array([[0.53481906, 0.18128046, 0.52370394, 0.20741472, 0.96021535,
        0.17722208],
       [0.        , 0.71901005, 0.79180779, 0.95237685, 0.52255864,
        0.03486268],
       [0.        , 0.        , 0.90377474, 0.86442553, 0.28793317,
        0.80192044],
       [0.        , 0.        , 0.        , 0.16058274, 0.67493355,
        0.18469104],
       [0.        , 0.        , 0.        , 0.        , 0.45512626,
        0.33510941],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.02514422]])

In [166]:
np.tril(arr)

array([[0.53481906, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.76153439, 0.71901005, 0.        , 0.        , 0.        ,
        0.        ],
       [0.18043538, 0.44763899, 0.90377474, 0.        , 0.        ,
        0.        ],
       [0.46966386, 0.43416453, 0.32167581, 0.16058274, 0.        ,
        0.        ],
       [0.18593542, 0.65227212, 0.87730055, 0.78394231, 0.45512626,
        0.        ],
       [0.10686434, 0.33274041, 0.42080667, 0.74802713, 0.41163675,
        0.02514422]])

8. Create a NumPy array of 20 elements and reshape it into:
○ 4 × 5 matrix
○ 2 × 10 matrix
○ 5 × 4 matrix

In [169]:
arr =np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [172]:
arr=np.reshape(arr,(4,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [173]:
arr=np.reshape(arr,(2,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [174]:
arr=np.reshape(arr,(5,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

9. Create a 5 × 5 matrix and calculate the sum of:
○ Each row
○ Each column

In [186]:
arr = np.arange(1,26).reshape(5,5)

arr.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [185]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

10. Create two arrays and find all common elements between them.

In [200]:
arr1 = np.random.rand(9)
arr2=np.random.rand(9)
common =np.intersect1d(arr1,arr2)
print(common)

[]


In [201]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([20, 40, 60, 80])
common =np.intersect1d(arr1,arr2)
print(common)


[20 40]


11. Create a 5 × 5 matrix and find the position (row and column index)
of the largest element.

In [ ]:
arr =np.array([1,2,34,5,24,2,4,24,2,4,65,67,5,4,64,6,56,5,6,5,75,34,56,45,6]).reshape(5,5)
arr


array([[ 1,  2, 34,  5, 24],
       [ 2,  4, 24,  2,  4],
       [65, 67,  5,  4, 64],
       [ 6, 56,  5,  6,  5],
       [75, 34, 56, 45,  6]])

In [211]:
 np.max(arr)


np.int64(75)

In [210]:
 np.argmax(arr)

np.int64(20)

In [212]:
np.unravel_index(np.argmax(arr),arr.shape)

(np.int64(4), np.int64(0))

12. Create a dataset of students' marks using a NumPy array and find:
● Highest marks
● Lowest marks
● Average marks
● Students scoring above average

In [214]:
arr = np.array([67,62,96,85,74,85,92,82,45,38,59,81,80,48])
print("Maximum marks",np.max(arr))

Maximum marks 96


In [215]:
print("Minimum marks",np.min(arr))

Minimum marks 38


In [217]:
print("Average marks",np.average(arr))

Average marks 71.0


In [225]:
above_average =arr[arr> np.average(arr)]
print(above_average)

[96 85 74 85 92 82 81 80]
